// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.32.0--rc1
// source: url_cutter.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ShortenRequestForBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CorrelationID string                 `protobuf:"bytes,1,opt,name=correlationID,proto3" json:"correlationID,omitempty"`
	OriginalURL   string                 `protobuf:"bytes,2,opt,name=originalURL,proto3" json:"originalURL,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShortenRequestForBatch) Reset() {
	*x = ShortenRequestForBatch{}
	mi := &file_url_cutter_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShortenRequestForBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortenRequestForBatch) ProtoMessage() {}

func (x *ShortenRequestForBatch) ProtoReflect() protoreflect.Message {
	mi := &file_url_cutter_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShortenRequestForBatch.ProtoReflect.Descriptor instead.
func (*ShortenRequestForBatch) Descriptor() ([]byte, []int) {
	return file_url_cutter_proto_rawDescGZIP(), []int{0}
}

func (x *ShortenRequestForBatch) GetCorrelationID() string {
	if x != nil {
		return x.CorrelationID
	}
	return ""
}

func (x *ShortenRequestForBatch) GetOriginalURL() string {
	if x != nil {
		return x.OriginalURL
	}
	return ""
}

type ShortenResponseForBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CorrelationID string                 `protobuf:"bytes,1,opt,name=correlationID,proto3" json:"correlationID,omitempty"`
	ShortURL      string                 `protobuf:"bytes,2,opt,name=shortURL,proto3" json:"shortURL,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShortenResponseForBatch) Reset() {
	*x = ShortenResponseForBatch{}
	mi := &file_url_cutter_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShortenResponseForBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortenResponseForBatch) ProtoMessage() {}

func (x *ShortenResponseForBatch) ProtoReflect() protoreflect.Message {
	mi := &file_url_cutter_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShortenResponseForBatch.ProtoReflect.Descriptor instead.
func (*ShortenResponseForBatch) Descriptor() ([]byte, []int) {
	return file_url_cutter_proto_rawDescGZIP(), []int{1}
}

func (x *ShortenResponseForBatch) GetCorrelationID() string {
	if x != nil {
		return x.CorrelationID
	}
	return ""
}

func (x *ShortenResponseForBatch) GetShortURL() string {
	if x != nil {
		return x.ShortURL
	}
	return ""
}

type ShortenOrigURLs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShortURL      string                 `protobuf:"bytes,1,opt,name=shortURL,proto3" json:"shortURL,omitempty"`
	OriginalURL   string                 `protobuf:"bytes,2,opt,name=originalURL,proto3" json:"originalURL,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShortenOrigURLs) Reset() {
	*x = ShortenOrigURLs{}
	mi := &file_url_cutter_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShortenOrigURLs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortenOrigURLs) ProtoMessage() {}

func (x *ShortenOrigURLs) ProtoReflect() protoreflect.Message {
	mi := &file_url_cutter_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShortenOrigURLs.ProtoReflect.Descriptor instead.
func (*ShortenOrigURLs) Descriptor() ([]byte, []int) {
	return file_url_cutter_proto_rawDescGZIP(), []int{2}
}

func (x *ShortenOrigURLs) GetShortURL() string {
	if x != nil {
		return x.ShortURL
	}
	return ""
}

func (x *ShortenOrigURLs) GetOriginalURL() string {
	if x != nil {
		return x.OriginalURL
	}
	return ""
}

type BatchShortenURLRequest struct {
	state           protoimpl.MessageState    `protogen:"open.v1"`
	ShortenRequests []*ShortenRequestForBatch `protobuf:"bytes,1,rep,name=shortenRequests,proto3" json:"shortenRequests,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *BatchShortenURLRequest) Reset() {
	*x = BatchShortenURLRequest{}
	mi := &file_url_cutter_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchShortenURLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchShortenURLRequest) ProtoMessage() {}

func (x *BatchShortenURLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_url_cutter_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchShortenURLRequest.ProtoReflect.Descriptor instead.
func (*BatchShortenURLRequest) Descriptor() ([]byte, []int) {
	return file_url_cutter_proto_rawDescGZIP(), []int{3}
}

func (x *BatchShortenURLRequest) GetShortenRequests() []*ShortenRequestForBatch {
	if x != nil {
		return x.ShortenRequests
	}
	return nil
}

type BatchShortenURLResponse struct {
	state            protoimpl.MessageState     `protogen:"open.v1"`
	ShortenResponses []*ShortenResponseForBatch `protobuf:"bytes,1,rep,name=shortenResponses,proto3" json:"shortenResponses,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *BatchShortenURLResponse) Reset() {
	*x = BatchShortenURLResponse{}
	mi := &file_url_cutter_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchShortenURLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchShortenURLResponse) ProtoMessage() {}

func (x *BatchShortenURLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_url_cutter_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchShortenURLResponse.ProtoReflect.Descriptor instead.
func (*BatchShortenURLResponse) Descriptor() ([]byte, []int) {
	return file_url_cutter_proto_rawDescGZIP(), []int{4}
}

func (x *BatchShortenURLResponse) GetShortenResponses() []*ShortenResponseForBatch {
	if x != nil {
		return x.ShortenResponses
	}
	return nil
}

type GetHandlerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHandlerRequest) Reset() {
	*x = GetHandlerRequest{}
	mi := &file_url_cutter_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHandlerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHandlerRequest) ProtoMessage() {}

func (x *GetHandlerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_url_cutter_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHandlerRequest.ProtoReflect.Descriptor instead.
func (*GetHandlerRequest) Descriptor() ([]byte, []int) {
	return file_url_cutter_proto_rawDescGZIP(), []int{5}
}

func (x *GetHandlerRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetHandlerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrigURL       string                 `protobuf:"bytes,1,opt,name=origURL,proto3" json:"origURL,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHandlerResponse) Reset() {
	*x = GetHandlerResponse{}
	mi := &file_url_cutter_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHandlerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHandlerResponse) ProtoMessage() {}

func (x *GetHandlerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_url_cutter_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHandlerResponse.ProtoReflect.Descriptor instead.
func (*GetHandlerResponse) Descriptor() ([]byte, []int) {
	return file_url_cutter_proto_rawDescGZIP(), []int{6}
}

func (x *GetHandlerResponse) GetOrigURL() string {
	if x != nil {
		return x.OrigURL
	}
	return ""
}

func (x *GetHandlerResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type PostHandlerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	UserID        int64                  `protobuf:"varint,2,opt,name=userID,proto3" json:"userID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostHandlerRequest) Reset() {
	*x = PostHandlerRequest{}
	mi := &file_url_cutter_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostHandlerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostHandlerRequest) ProtoMessage() {}

func (x *PostHandlerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_url_cutter_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostHandlerRequest.ProtoReflect.Descriptor instead.
func (*PostHandlerRequest) Descriptor() ([]byte, []int) {
	return file_url_cutter_proto_rawDescGZIP(), []int{7}
}

func (x *PostHandlerRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *PostHandlerRequest) GetUserID() int64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

type PostHandlerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShortUrl      string                 `protobuf:"bytes,1,opt,name=short_url,json=shortUrl,proto3" json:"short_url,omitempty"`
	UserID        int64                  `protobuf:"varint,2,opt,name=userID,proto3" json:"userID,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostHandlerResponse) Reset() {
	*x = PostHandlerResponse{}
	mi := &file_url_cutter_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostHandlerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostHandlerResponse) ProtoMessage() {}

func (x *PostHandlerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_url_cutter_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostHandlerResponse.ProtoReflect.Descriptor instead.
func (*PostHandlerResponse) Descriptor() ([]byte, []int) {
	return file_url_cutter_proto_rawDescGZIP(), []int{8}
}

func (x *PostHandlerResponse) GetShortUrl() string {
	if x != nil {
		return x.ShortUrl
	}
	return ""
}

func (x *PostHandlerResponse) GetUserID() int64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *PostHandlerResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type JSONPostHandlerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JSONPostHandlerRequest) Reset() {
	*x = JSONPostHandlerRequest{}
	mi := &file_url_cutter_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JSONPostHandlerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JSONPostHandlerRequest) ProtoMessage() {}

func (x *JSONPostHandlerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_url_cutter_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JSONPostHandlerRequest.ProtoReflect.Descriptor instead.
func (*JSONPostHandlerRequest) Descriptor() ([]byte, []int) {
	return file_url_cutter_proto_rawDescGZIP(), []int{9}
}

func (x *JSONPostHandlerRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type JSONPostHandlerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShortUrl      string                 `protobuf:"bytes,1,opt,name=short_url,json=shortUrl,proto3" json:"short_url,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JSONPostHandlerResponse) Reset() {
	*x = JSONPostHandlerResponse{}
	mi := &file_url_cutter_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JSONPostHandlerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JSONPostHandlerResponse) ProtoMessage() {}

func (x *JSONPostHandlerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_url_cutter_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JSONPostHandlerResponse.ProtoReflect.Descriptor instead.
func (*JSONPostHandlerResponse) Descriptor() ([]byte, []int) {
	return file_url_cutter_proto_rawDescGZIP(), []int{10}
}

func (x *JSONPostHandlerResponse) GetShortUrl() string {
	if x != nil {
		return x.ShortUrl
	}
	return ""
}

func (x *JSONPostHandlerResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type DBPingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DBPingResponse) Reset() {
	*x = DBPingResponse{}
	mi := &file_url_cutter_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DBPingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DBPingResponse) ProtoMessage() {}

func (x *DBPingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_url_cutter_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DBPingResponse.ProtoReflect.Descriptor instead.
func (*DBPingResponse) Descriptor() ([]byte, []int) {
	return file_url_cutter_proto_rawDescGZIP(), []int{11}
}

func (x *DBPingResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GetUserUrlsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserID        int64                  `protobuf:"varint,1,opt,name=userID,proto3" json:"userID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserUrlsRequest) Reset() {
	*x = GetUserUrlsRequest{}
	mi := &file_url_cutter_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserUrlsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserUrlsRequest) ProtoMessage() {}

func (x *GetUserUrlsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_url_cutter_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserUrlsRequest.ProtoReflect.Descriptor instead.
func (*GetUserUrlsRequest) Descriptor() ([]byte, []int) {
	return file_url_cutter_proto_rawDescGZIP(), []int{12}
}

func (x *GetUserUrlsRequest) GetUserID() int64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

type GetUserUrlsResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ShortenResponse []*ShortenOrigURLs     `protobuf:"bytes,1,rep,name=shortenResponse,proto3" json:"shortenResponse,omitempty"`
	Error           string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetUserUrlsResponse) Reset() {
	*x = GetUserUrlsResponse{}
	mi := &file_url_cutter_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserUrlsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserUrlsResponse) ProtoMessage() {}

func (x *GetUserUrlsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_url_cutter_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserUrlsResponse.ProtoReflect.Descriptor instead.
func (*GetUserUrlsResponse) Descriptor() ([]byte, []int) {
	return file_url_cutter_proto_rawDescGZIP(), []int{13}
}

func (x *GetUserUrlsResponse) GetShortenResponse() []*ShortenOrigURLs {
	if x != nil {
		return x.ShortenResponse
	}
	return nil
}

func (x *GetUserUrlsResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type DeleteUrlsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Urls          []string               `protobuf:"bytes,1,rep,name=urls,proto3" json:"urls,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUrlsRequest) Reset() {
	*x = DeleteUrlsRequest{}
	mi := &file_url_cutter_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUrlsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUrlsRequest) ProtoMessage() {}

func (x *DeleteUrlsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_url_cutter_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUrlsRequest.ProtoReflect.Descriptor instead.
func (*DeleteUrlsRequest) Descriptor() ([]byte, []int) {
	return file_url_cutter_proto_rawDescGZIP(), []int{14}
}

func (x *DeleteUrlsRequest) GetUrls() []string {
	if x != nil {
		return x.Urls
	}
	return nil
}

type DeleteUrlsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUrlsResponse) Reset() {
	*x = DeleteUrlsResponse{}
	mi := &file_url_cutter_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUrlsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUrlsResponse) ProtoMessage() {}

func (x *DeleteUrlsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_url_cutter_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUrlsResponse.ProtoReflect.Descriptor instead.
func (*DeleteUrlsResponse) Descriptor() ([]byte, []int) {
	return file_url_cutter_proto_rawDescGZIP(), []int{15}
}

func (x *DeleteUrlsResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GetStatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Urls          int64                  `protobuf:"varint,1,opt,name=urls,proto3" json:"urls,omitempty"`
	Users         int64                  `protobuf:"varint,2,opt,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatsResponse) Reset() {
	*x = GetStatsResponse{}
	mi := &file_url_cutter_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatsResponse) ProtoMessage() {}

func (x *GetStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_url_cutter_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatsResponse.ProtoReflect.Descriptor instead.
func (*GetStatsResponse) Descriptor() ([]byte, []int) {
	return file_url_cutter_proto_rawDescGZIP(), []int{16}
}

func (x *GetStatsResponse) GetUrls() int64 {
	if x != nil {
		return x.Urls
	}
	return 0
}

func (x *GetStatsResponse) GetUsers() int64 {
	if x != nil {
		return x.Users
	}
	return 0
}

var File_url_cutter_proto protoreflect.FileDescriptor

const file_url_cutter_proto_rawDesc = "" +
	"\n" +
	"\x10url_cutter.proto\x12\turlCutter\x1a\x1bgoogle/protobuf/empty.proto\"`\n" +
	"\x16ShortenRequestForBatch\x12$\n" +
	"\rcorrelationID\x18\x01 \x01(\tR\rcorrelationID\x12 \n" +
	"\voriginalURL\x18\x02 \x01(\tR\voriginalURL\"[\n" +
	"\x17ShortenResponseForBatch\x12$\n" +
	"\rcorrelationID\x18\x01 \x01(\tR\rcorrelationID\x12\x1a\n" +
	"\bshortURL\x18\x02 \x01(\tR\bshortURL\"O\n" +
	"\x0fShortenOrigURLs\x12\x1a\n" +
	"\bshortURL\x18\x01 \x01(\tR\bshortURL\x12 \n" +
	"\voriginalURL\x18\x02 \x01(\tR\voriginalURL\"e\n" +
	"\x16BatchShortenURLRequest\x12K\n" +
	"\x0fshortenRequests\x18\x01 \x03(\v2!.urlCutter.ShortenRequestForBatchR\x0fshortenRequests\"i\n" +
	"\x17BatchShortenURLResponse\x12N\n" +
	"\x10shortenResponses\x18\x01 \x03(\v2\".urlCutter.ShortenResponseForBatchR\x10shortenResponses\"#\n" +
	"\x11GetHandlerRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"D\n" +
	"\x12GetHandlerResponse\x12\x18\n" +
	"\aorigURL\x18\x01 \x01(\tR\aorigURL\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\">\n" +
	"\x12PostHandlerRequest\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x16\n" +
	"\x06userID\x18\x02 \x01(\x03R\x06userID\"`\n" +
	"\x13PostHandlerResponse\x12\x1b\n" +
	"\tshort_url\x18\x01 \x01(\tR\bshortUrl\x12\x16\n" +
	"\x06userID\x18\x02 \x01(\x03R\x06userID\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"*\n" +
	"\x16JSONPostHandlerRequest\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\"L\n" +
	"\x17JSONPostHandlerResponse\x12\x1b\n" +
	"\tshort_url\x18\x01 \x01(\tR\bshortUrl\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"&\n" +
	"\x0eDBPingResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\",\n" +
	"\x12GetUserUrlsRequest\x12\x16\n" +
	"\x06userID\x18\x01 \x01(\x03R\x06userID\"q\n" +
	"\x13GetUserUrlsResponse\x12D\n" +
	"\x0fshortenResponse\x18\x01 \x03(\v2\x1a.urlCutter.ShortenOrigURLsR\x0fshortenResponse\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"'\n" +
	"\x11DeleteUrlsRequest\x12\x12\n" +
	"\x04urls\x18\x01 \x03(\tR\x04urls\"*\n" +
	"\x12DeleteUrlsResponse\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"<\n" +
	"\x10GetStatsResponse\x12\x12\n" +
	"\x04urls\x18\x01 \x01(\x03R\x04urls\x12\x14\n" +
	"\x05users\x18\x02 \x01(\x03R\x05users2\xef\x04\n" +
	"\tURLCutter\x12X\n" +
	"\x0fBatchShortenURL\x12!.urlCutter.BatchShortenURLRequest\x1a\".urlCutter.BatchShortenURLResponse\x12I\n" +
	"\n" +
	"GetHandler\x12\x1c.urlCutter.GetHandlerRequest\x1a\x1d.urlCutter.GetHandlerResponse\x12L\n" +
	"\vPostHandler\x12\x1d.urlCutter.PostHandlerRequest\x1a\x1e.urlCutter.PostHandlerResponse\x12X\n" +
	"\x0fJSONPostHandler\x12!.urlCutter.JSONPostHandlerRequest\x1a\".urlCutter.JSONPostHandlerResponse\x12;\n" +
	"\x06DBPing\x12\x16.google.protobuf.Empty\x1a\x19.urlCutter.DBPingResponse\x12L\n" +
	"\vGetUserUrls\x12\x1d.urlCutter.GetUserUrlsRequest\x1a\x1e.urlCutter.GetUserUrlsResponse\x12I\n" +
	"\n" +
	"DeleteUrls\x12\x1c.urlCutter.DeleteUrlsRequest\x1a\x1d.urlCutter.DeleteUrlsResponse\x12?\n" +
	"\bGetStats\x12\x16.google.protobuf.Empty\x1a\x1b.urlCutter.GetStatsResponseB\x04Z\x02.;b\x06proto3"

var (
	file_url_cutter_proto_rawDescOnce sync.Once
	file_url_cutter_proto_rawDescData []byte
)

func file_url_cutter_proto_rawDescGZIP() []byte {
	file_url_cutter_proto_rawDescOnce.Do(func() {
		file_url_cutter_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_url_cutter_proto_rawDesc), len(file_url_cutter_proto_rawDesc)))
	})
	return file_url_cutter_proto_rawDescData
}

var file_url_cutter_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_url_cutter_proto_goTypes = []any{
	(*ShortenRequestForBatch)(nil),  // 0: urlCutter.ShortenRequestForBatch
	(*ShortenResponseForBatch)(nil), // 1: urlCutter.ShortenResponseForBatch
	(*ShortenOrigURLs)(nil),         // 2: urlCutter.ShortenOrigURLs
	(*BatchShortenURLRequest)(nil),  // 3: urlCutter.BatchShortenURLRequest
	(*BatchShortenURLResponse)(nil), // 4: urlCutter.BatchShortenURLResponse
	(*GetHandlerRequest)(nil),       // 5: urlCutter.GetHandlerRequest
	(*GetHandlerResponse)(nil),      // 6: urlCutter.GetHandlerResponse
	(*PostHandlerRequest)(nil),      // 7: urlCutter.PostHandlerRequest
	(*PostHandlerResponse)(nil),     // 8: urlCutter.PostHandlerResponse
	(*JSONPostHandlerRequest)(nil),  // 9: urlCutter.JSONPostHandlerRequest
	(*JSONPostHandlerResponse)(nil), // 10: urlCutter.JSONPostHandlerResponse
	(*DBPingResponse)(nil),          // 11: urlCutter.DBPingResponse
	(*GetUserUrlsRequest)(nil),      // 12: urlCutter.GetUserUrlsRequest
	(*GetUserUrlsResponse)(nil),     // 13: urlCutter.GetUserUrlsResponse
	(*DeleteUrlsRequest)(nil),       // 14: urlCutter.DeleteUrlsRequest
	(*DeleteUrlsResponse)(nil),      // 15: urlCutter.DeleteUrlsResponse
	(*GetStatsResponse)(nil),        // 16: urlCutter.GetStatsResponse
	(*emptypb.Empty)(nil),           // 17: google.protobuf.Empty
}
var file_url_cutter_proto_depIdxs = []int32{
	0,  // 0: urlCutter.BatchShortenURLRequest.shortenRequests:type_name -> urlCutter.ShortenRequestForBatch
	1,  // 1: urlCutter.BatchShortenURLResponse.shortenResponses:type_name -> urlCutter.ShortenResponseForBatch
	2,  // 2: urlCutter.GetUserUrlsResponse.shortenResponse:type_name -> urlCutter.ShortenOrigURLs
	3,  // 3: urlCutter.URLCutter.BatchShortenURL:input_type -> urlCutter.BatchShortenURLRequest
	5,  // 4: urlCutter.URLCutter.GetHandler:input_type -> urlCutter.GetHandlerRequest
	7,  // 5: urlCutter.URLCutter.PostHandler:input_type -> urlCutter.PostHandlerRequest
	9,  // 6: urlCutter.URLCutter.JSONPostHandler:input_type -> urlCutter.JSONPostHandlerRequest
	17, // 7: urlCutter.URLCutter.DBPing:input_type -> google.protobuf.Empty
	12, // 8: urlCutter.URLCutter.GetUserUrls:input_type -> urlCutter.GetUserUrlsRequest
	14, // 9: urlCutter.URLCutter.DeleteUrls:input_type -> urlCutter.DeleteUrlsRequest
	17, // 10: urlCutter.URLCutter.GetStats:input_type -> google.protobuf.Empty
	4,  // 11: urlCutter.URLCutter.BatchShortenURL:output_type -> urlCutter.BatchShortenURLResponse
	6,  // 12: urlCutter.URLCutter.GetHandler:output_type -> urlCutter.GetHandlerResponse
	8,  // 13: urlCutter.URLCutter.PostHandler:output_type -> urlCutter.PostHandlerResponse
	10, // 14: urlCutter.URLCutter.JSONPostHandler:output_type -> urlCutter.JSONPostHandlerResponse
	11, // 15: urlCutter.URLCutter.DBPing:output_type -> urlCutter.DBPingResponse
	13, // 16: urlCutter.URLCutter.GetUserUrls:output_type -> urlCutter.GetUserUrlsResponse
	15, // 17: urlCutter.URLCutter.DeleteUrls:output_type -> urlCutter.DeleteUrlsResponse
	16, // 18: urlCutter.URLCutter.GetStats:output_type -> urlCutter.GetStatsResponse
	11, // [11:19] is the sub-list for method output_type
	3,  // [3:11] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_url_cutter_proto_init() }
func file_url_cutter_proto_init() {
	if File_url_cutter_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_url_cutter_proto_rawDesc), len(file_url_cutter_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_url_cutter_proto_goTypes,
		DependencyIndexes: file_url_cutter_proto_depIdxs,
		MessageInfos:      file_url_cutter_proto_msgTypes,
	}.Build()
	File_url_cutter_proto = out.File
	file_url_cutter_proto_goTypes = nil
	file_url_cutter_proto_depIdxs = nil
}
