// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.0--rc1
// source: url_cutter.proto

package __

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	URLCutter_Pos_FullMethodName = "/urlCutter.URLCutter/Pos"
)

// URLCutterClient is the client API for URLCutter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type URLCutterClient interface {
	Pos(ctx context.Context, in *PostHandlerRequest, opts ...grpc.CallOption) (*PostHandlerResponse, error)
}

type uRLCutterClient struct {
	cc grpc.ClientConnInterface
}

func NewURLCutterClient(cc grpc.ClientConnInterface) URLCutterClient {
	return &uRLCutterClient{cc}
}

func (c *uRLCutterClient) Pos(ctx context.Context, in *PostHandlerRequest, opts ...grpc.CallOption) (*PostHandlerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PostHandlerResponse)
	err := c.cc.Invoke(ctx, URLCutter_Pos_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// URLCutterServer is the server API for URLCutter service.
// All implementations must embed UnimplementedURLCutterServer
// for forward compatibility.
type URLCutterServer interface {
	Pos(context.Context, *PostHandlerRequest) (*PostHandlerResponse, error)
	mustEmbedUnimplementedURLCutterServer()
}

// UnimplementedURLCutterServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedURLCutterServer struct{}

func (UnimplementedURLCutterServer) Pos(context.Context, *PostHandlerRequest) (*PostHandlerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Pos not implemented")
}
func (UnimplementedURLCutterServer) mustEmbedUnimplementedURLCutterServer() {}
func (UnimplementedURLCutterServer) testEmbeddedByValue()                   {}

// UnsafeURLCutterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to URLCutterServer will
// result in compilation errors.
type UnsafeURLCutterServer interface {
	mustEmbedUnimplementedURLCutterServer()
}

func RegisterURLCutterServer(s grpc.ServiceRegistrar, srv URLCutterServer) {
	// If the following call pancis, it indicates UnimplementedURLCutterServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&URLCutter_ServiceDesc, srv)
}

func _URLCutter_Pos_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostHandlerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(URLCutterServer).Pos(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: URLCutter_Pos_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(URLCutterServer).Pos(ctx, req.(*PostHandlerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// URLCutter_ServiceDesc is the grpc.ServiceDesc for URLCutter service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var URLCutter_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "urlCutter.URLCutter",
	HandlerType: (*URLCutterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Pos",
			Handler:    _URLCutter_Pos_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "url_cutter.proto",
}
