// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.32.0--rc1
// source: url_cutter.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PostHandlerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostHandlerRequest) Reset() {
	*x = PostHandlerRequest{}
	mi := &file_url_cutter_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostHandlerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostHandlerRequest) ProtoMessage() {}

func (x *PostHandlerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_url_cutter_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostHandlerRequest.ProtoReflect.Descriptor instead.
func (*PostHandlerRequest) Descriptor() ([]byte, []int) {
	return file_url_cutter_proto_rawDescGZIP(), []int{0}
}

func (x *PostHandlerRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type PostHandlerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShortUrl      string                 `protobuf:"bytes,1,opt,name=short_url,json=shortUrl,proto3" json:"short_url,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"` // ошибка
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostHandlerResponse) Reset() {
	*x = PostHandlerResponse{}
	mi := &file_url_cutter_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostHandlerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostHandlerResponse) ProtoMessage() {}

func (x *PostHandlerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_url_cutter_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostHandlerResponse.ProtoReflect.Descriptor instead.
func (*PostHandlerResponse) Descriptor() ([]byte, []int) {
	return file_url_cutter_proto_rawDescGZIP(), []int{1}
}

func (x *PostHandlerResponse) GetShortUrl() string {
	if x != nil {
		return x.ShortUrl
	}
	return ""
}

func (x *PostHandlerResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_url_cutter_proto protoreflect.FileDescriptor

const file_url_cutter_proto_rawDesc = "" +
	"\n" +
	"\x10url_cutter.proto\x12\turlCutter\"&\n" +
	"\x12PostHandlerRequest\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\"H\n" +
	"\x13PostHandlerResponse\x12\x1b\n" +
	"\tshort_url\x18\x01 \x01(\tR\bshortUrl\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error2Q\n" +
	"\tURLCutter\x12D\n" +
	"\x03Pos\x12\x1d.urlCutter.PostHandlerRequest\x1a\x1e.urlCutter.PostHandlerResponseB\x04Z\x02.;b\x06proto3"

var (
	file_url_cutter_proto_rawDescOnce sync.Once
	file_url_cutter_proto_rawDescData []byte
)

func file_url_cutter_proto_rawDescGZIP() []byte {
	file_url_cutter_proto_rawDescOnce.Do(func() {
		file_url_cutter_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_url_cutter_proto_rawDesc), len(file_url_cutter_proto_rawDesc)))
	})
	return file_url_cutter_proto_rawDescData
}

var file_url_cutter_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_url_cutter_proto_goTypes = []any{
	(*PostHandlerRequest)(nil),  // 0: urlCutter.PostHandlerRequest
	(*PostHandlerResponse)(nil), // 1: urlCutter.PostHandlerResponse
}
var file_url_cutter_proto_depIdxs = []int32{
	0, // 0: urlCutter.URLCutter.Pos:input_type -> urlCutter.PostHandlerRequest
	1, // 1: urlCutter.URLCutter.Pos:output_type -> urlCutter.PostHandlerResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_url_cutter_proto_init() }
func file_url_cutter_proto_init() {
	if File_url_cutter_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_url_cutter_proto_rawDesc), len(file_url_cutter_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_url_cutter_proto_goTypes,
		DependencyIndexes: file_url_cutter_proto_depIdxs,
		MessageInfos:      file_url_cutter_proto_msgTypes,
	}.Build()
	File_url_cutter_proto = out.File
	file_url_cutter_proto_goTypes = nil
	file_url_cutter_proto_depIdxs = nil
}
